client1:
  coordinator:
    class: e_tree_learning.roles.coordinator.ELCoordinator
    impl:
      model:
        class: e_tree_learning.workload.lenet_5.MyLeNet5RGBModel
      dataset:
        constructor_args:
          dataset:
            type: e_tree_learning.workload.cifar_10.MyCiFar10Dataset
            options:
              root: /home/roleml/datasets/cifar-10
              part: test
          converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
          sampler: sequential
          combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
  aggregator-1:
    class: e_tree_learning.roles.aggregator.LayeredCollectiveAggregator
    options:
      layer: 1
      num_steps: 1
    impl:
      merger:
        class: roleml.library.workload.util.collections.merger.torch.TorchStateDictAverager
client[1-3]:
  aggregator-0:
    class: e_tree_learning.roles.aggregator.LayeredCollectiveAggregator
    options:
      layer: 0
      num_steps: 2
    impl:
      merger:
        class: roleml.library.workload.util.collections.merger.torch.TorchStateDictAverager
client(1|2|3|4|5|6|7|8|9|10):
  trainer:
    class: e_tree_learning.roles.trainer.MyEpochTrainer
    impl:
      model:
        class: e_tree_learning.workload.lenet_5.MyLeNet5RGBModel
        constructor_args:
          lr: 0.01
          device: cpu
          num_threads: 4
      dataset:
        constructor_args:
          dataset:
            type: e_tree_learning.workload.cifar_10.MyCiFar10SlicedDataset
            options:
              root: /home/roleml/datasets/cifar-10/sliced
              index: $c[4-20]
          converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
          sampler: sequential
          batch_size: 32
          combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
