connection_rules:
  - client1 client(4|7|9)
  - client2 client(5|8)
  - client3 client(4|9)
  - client4 client(1|3|8)
  - client5 client(2|6|7)
  - client6 client(5|8|10)
  - client7 client(1|5)
  - client8 client(2|4|6)
  - client9 client(1|3|10)
  - client10 client(6|9)

relationship_rules:
  client1:
    peer: client(4|7|9)/aggregator    # node-name/role-instance-name (if instance name not provided, relationship name is used)
  client2:
    peer: client(5|8)/aggregator
  client3:
    peer: client(4|9)/aggregator
  client4:
    peer: client(1|3|8)/aggregator
  client5:
    peer: client(2|6|7)/aggregator
  client6:
    peer: client(5|8|10)/aggregator
  client7:
    peer: client(1|5)/aggregator
  client8:
    peer: client(2|4|6)/aggregator
  client9:
    peer: client(1|3|10)/aggregator
  client10:
    peer: client(6|9)/aggregator
  conductor:
    coordinator: client(1|2|3|4|5|6|7|8|9|10)/coordinator
