connection_rules:
  - client1 client(2|3)
  - client2 client(1|3)
  - client3 client(1|2)

relationship_rules:
  client1:
    peer: client2/aggregator
  client2:
    peer: client3/aggregator
  client3:
    peer: client1/aggregator
  conductor:
    coordinator: client(1|2|3)/coordinator
