profiles:
  - name: client1
    address: 127.0.0.1:5011
  - name: client2
    address: 127.0.0.1:5002
  - name: client3
    address: 127.0.0.1:5003
  - name: client4
    address: 127.0.0.1:5004
  - name: client5
    address: 127.0.0.1:5005
  - name: client6
    address: 127.0.0.1:5006
