model:
  loader:
    method: factory
    target: federated_learning.workload.mobilenet_v3.MyMobileNetV3SmallModel
dataset:
  loader:
    method: factory
    target: federated_learning.workload.imagenet_100.MyImageNet100TestDataset
    args:
      root: /home/roleml/datasets/imagenet-100
      samples: 5000
      batch_size: 32
      transform: roleml.library.workload.datasets.zoo.image.imagenet_100.functions.default_transform
