connection_rules:
  - client1 client(10|6)
  - client2 client(6|7)
  - client3 client(7|8)
  - client4 client(8|9)
  - client5 client(9|10)
  - client6 client(1|2)
  - client7 client(2|3)
  - client8 client(3|4)
  - client9 client(4|5)
  - client10 client(5|1)

relationship_rules:
  client1:
    peer: client(10|6)/aggregator    # node-name/role-instance-name (if instance name not provided, relationship name is used)
  client2:
    peer: client(6|7)/aggregator
  client3:
    peer: client(7|8)/aggregator
  client4:
    peer: client(8|9)/aggregator
  client5:
    peer: client(9|10)/aggregator
  client6:
    peer: client(1|2)/aggregator
    relevant-coordinator : client(1|2)/coordinator
  client7:
    peer: client(2|3)/aggregator
    relevant-coordinator : client(2|3)/coordinator
  client8:
    peer: client(3|4)/aggregator
    relevant-coordinator : client(3|4)/coordinator
  client9:
    peer: client(4|5)/aggregator
    relevant-coordinator : client(4|5)/coordinator
  client10:
    peer: client(5|1)/aggregator
    relevant-coordinator : client(5|1)/coordinator
  conductor:
    active-coordinator: client(1|2|3|4|5)/coordinator
    passive-coordinator: client(10|6|7|8|9)/coordinator
