<<: !include ./topo/default-with-registration-containerized.yaml
profiles: !include ./nodes/medium.yaml profiles
roles: !include ./roles/fedavg-v2-with-registration.yaml
deployment_order:
  - server  # we only need to declare that the server must be deployed first
