# affects batch nodes (started on current machine)
client.*:   # node name (RegEx)
  trainer:  # role instance name
    class: gossip_learning.roles.trainer.MyEpochTrainer
    impl:
      model:
        loader:
          method: factory
          target: gossip_learning.workload.lenet_5.MyLeNet5RGBModel
          args:
            lr: 0.01
            device: cpu
            num_threads: 2
      dataset:
        loader:
          method: factory
          target: roleml.library.workload.datasets.views.DatasetViewFactory
          args:
            dataset:
              type: gossip_learning.workload.cifar_10.MyCiFar10SlicedDataset
              options:
                root: /home/roleml/datasets/cifar-10/sliced
                index: $c[0-9]
            converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
            sampler: sequential
            batch_size: 32
            combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
        eager_load: True
      dataset_test:
        loader:
          method: factory
          target: roleml.library.workload.datasets.views.DatasetViewFactory
          args:
            dataset:
              type: gossip_learning.workload.cifar_10.MyCiFar10Dataset
              options:
                root: /home/roleml/datasets/cifar-10
                part: test
            converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
            sampler: sequential
            combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
        eager_load: True
  aggregator:
    class: gossip_learning.roles.aggregator.GossipAggregator
    impl:
      buffer:
        loader:
          method: factory
          target: roleml.library.workload.util.collections.merger.torch.TorchStateDictCumulator
        eager_load: True
  coordinator:
    class: gossip_learning.roles.coordinator.GLCoordinator
    impl:
      merge-op:
        loader:
          method: direct-import
          target: gossip_learning.workload.ops.drop_local
