# affects batch nodes (started on current machine)
client.*:   # node name (RegEx)
  trainer:  # role instance name
    class: ring_all_reduce.roles.trainer.MyGradientsTrainer
    impl:
      model:
        loader:
          method: factory
          target: ring_all_reduce.workload.lenet_5.MyLeNet5RGBModel
          args:
            lr: 0.01
            device: cpu
            num_threads: 4
      dataset:
        loader:
          method: factory
          target: roleml.library.workload.datasets.views.DatasetViewFactory
          args:
            dataset:
              type: ring_all_reduce.workload.cifar_10.MyCiFar10SlicedDataset
              options:
                root: /home/roleml/datasets/cifar-10/sliced
                index: $c[0-9]
            converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
            sampler: sequential
            batch_size: 32
            combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
  aggregator:
    class: ring_all_reduce.roles.aggregator.AllReduceAggregator
    options:
      client_id: $c[0-9]
      num_clients: 10
      collect_channel: 'compute-gradients'
      apply_update_channel: 'apply-gradients'
      source_relationship: 'trainer'
    impl:
      split-op:
        loader:
          method: direct-import
          target: ring_all_reduce.workload.ops.split_gradients
      recover-op:
        loader:
          method: direct-import
          target: torch.cat

global:
  coordinator:
    class: ring_all_reduce.roles.coordinator.AllReduceGlobalCoordinator
    options:
      num_clients: 10
    impl:
      model:
        loader:
          method: factory
          target: ring_all_reduce.workload.lenet_5.MyLeNet5RGBModel
          args:
            lr: 0.01
            device: cpu
            num_threads: 4
      dataset_test:
        loader:
          method: factory
          target: roleml.library.workload.datasets.views.DatasetViewFactory
          args:
            dataset:
              type: ring_all_reduce.workload.cifar_10.MyCiFar10Dataset
              options:
                root: /home/roleml/datasets/cifar-10
                part: test
            converters: [roleml.library.workload.datasets.zoo.image.cifar_10.functions.transform_torch]
            sampler: sequential
            combiner: roleml.library.workload.datasets.zoo.image.cifar_10.functions.combine
        eager_load: True
      init-op:
        loader:
          method: direct-import
          target: ring_all_reduce.workload.ops.he_initialization
