name: client1
address: 0.0.0.0:5000
# procedure_invoker: roleml.extensions.messaging.default.separate.DefaultProcedureInvoker
# procedure_provider: roleml.extensions.messaging.default.separate.DefaultProcedureProvider
messaging_component: roleml.extensions.messaging.default.comb.DefaultMessagingComponent
collective_implementor: roleml.core.actor.group.impl.threaded.ThreadedCollectiveImplementor
contacts:
  conductor: 10.184.102.1:4000
relationships:
  manager: conductor/conductor
log_file_path: logs/$time
log_console_type: single
debug: true


base_image: python:3.11.10-bullseye
mounts: [
  "/home/roleml/cifar-10/batches:/home/roleml/datasets/cifar-10",
  "/home/roleml/cifar-10/batches_sliced:/home/roleml/datasets/cifar-10/sliced",
  "/home/roleml/roleml-refactor/RoleML:/roleml" # mount roleml source code into container
]
temp_dir: /home/liwh/roleml-refactor/temp
