# large setup - 20 client nodes
profiles:
  - name: server
    address: 127.0.0.1:5000
  - name: client1
    address: 127.0.0.1:5001
  - name: client2
    address: 127.0.0.1:5002
  - name: client3
    address: 127.0.0.1:5003
  - name: client4
    address: 127.0.0.1:5004
  - name: client5
    address: 127.0.0.1:5005
  - name: client6
    address: 127.0.0.1:5006
  - name: client7
    address: 127.0.0.1:5007
  - name: client8
    address: 127.0.0.1:5008
  - name: client9
    address: 127.0.0.1:5009
  - name: client10
    address: 127.0.0.1:5010
  - name: client11
    address: 127.0.0.1:5011
  - name: client12
    address: 127.0.0.1:5012
  - name: client13
    address: 127.0.0.1:5013
  - name: client14
    address: 127.0.0.1:5014
  - name: client15
    address: 127.0.0.1:5015
  - name: client16
    address: 127.0.0.1:5016
  - name: client17
    address: 127.0.0.1:5017
  - name: client18
    address: 127.0.0.1:5018
  - name: client19
    address: 127.0.0.1:5019
  - name: client20
    address: 127.0.0.1:5020
