profiles:
# Batch of nodes that will be started at the current machine
  - name: server
    address: 192.168.2.3:5000
  - name: client2
    address: 192.168.2.3:5002
  - name: client3
    address: 192.168.2.3:5003
  - name: client4
    address: 192.168.2.3:5004
  - name: client5
    address: 192.168.2.3:5005
  - name: client6
    address: 192.168.2.3:5006

profiles_individual:
# Nodes that will be started in other places (e.g. real edge devices)
  - name: client1
    address: 192.168.2.7:5000
