connection_rules:
  - client1 client(10|2)
  - client2 client(1|3)
  - client3 client(2|4)
  - client4 client(3|5)
  - client5 client(4|6)
  - client6 client(5|7)
  - client7 client(6|8)
  - client8 client(7|9)
  - client9 client(8|10)
  - client10 client(9|1)
  - global client.*
  - client.* global

relationship_rules:
  client1:
    peer-aggregator: client2/aggregator
  client2:
    peer-aggregator: client3/aggregator
  client3:
    peer-aggregator: client4/aggregator
  client4:
    peer-aggregator: client5/aggregator
  client5:
    peer-aggregator: client6/aggregator
  client6:
    peer-aggregator: client7/aggregator
  client7:
    peer-aggregator: client8/aggregator
  client8:
    peer-aggregator: client9/aggregator
  client9:
    peer-aggregator: client10/aggregator
  client10:
    peer-aggregator: client1/aggregator
  conductor:
    coordinator: global/coordinator
  global:
    aggregator: client.*/aggregator
    trainer: client.*/trainer
