# affects batch nodes (started on current machine)
client.*:
  trainer:
    class: federated_learning.roles.fedavg.trainer.MyEpochTrainer
    impl: !include ../workload/lenet-5-with-cifar-10/client.yaml
  # for handshake; make sure it is deployed last
  initiator:
    class: federated_learning.roles.handshake.client.MyClientInitiator
server:
  aggregator:
    class: federated_learning.roles.fedavg.v2.aggregator.WeightedCollectiveAggregator
    impl:
      merger:
        initializer:
          method: factory
          target: roleml.library.workload.util.collections.merger.torch.WeightedTorchStateDictAverager
  coordinator:
    class: federated_learning.roles.fedavg.coordinator.FLCoordinator
    options:
      deliver_final_model: true
    impl: !include ../workload/lenet-5-with-cifar-10/client.yaml
  client-selector:
    class: federated_learning.roles.client_selector.ClientSelector
  configurator:
    class: federated_learning.roles.fedavg.configurator.ClientConfigurator
  # for handshake (and call Coordinator)
  initiator:
    class: federated_learning.roles.handshake.server.MyServerInitiator
    options:
      relationship_name: trainer
      min_clients: 10
      max_seconds: 3600
      # FL run config
      <<: !include ../../runs/default.yaml fl_config
