# affects batch nodes (started on current machine)
client.*:
  trainer:
    class: federated_learning.roles.fednova.trainer.StepsAwareTrainer
    impl: !include ../workload/mobilenet-v3-small-with-imagenet-100/client.yaml
server:
  aggregator:
    class: federated_learning.roles.fednova.aggregator.StepNormalizingCollectiveAggregator
    impl:
      ops:
        loader:
          method: factory
          target: roleml.library.workload.util.arithmetic.torch.TorchStateDictArithmeticOps
  coordinator:
    class: federated_learning.roles.fednova.coordinator.FedNovaCoordinator
    # options:
    #   deliver_final_model: true
    impl:
      model: !include ../workload/mobilenet-v3-small-with-imagenet-100/server.yaml model
  client-selector:
    class: federated_learning.roles.client_selector.ClientSelector
  configurator:
    class: federated_learning.roles.fednova.configurator.ClientConfigurator
    options:
      base_epochs_map: !include base_epochs_map.yaml
